### ISSUE TITLE
Libraries should not commit Cargo.lock

### ISSUE THREAD

**Issue by mcarton** [killercup/rust-docstrings#8]
@killercup this seems to be [a volontary act](https://github.com/killercup/rust-docstrings/commit/84689e7824daa0eb22bb35c42efef214e6115fd8), why did you do that?

**Comment by killercup** [comment]
Yes, that was on purpose. So, in the end:

- Cargo ignores the lockfile of libraries by default, so the file doesn't hurt.
- The file allows one to see what actual version worked once upon a time (when bad comes to worst and a dependency had a breaking change in a minor version).
- We actually have binaries: The examples.

**Comment by mcarton** [comment]
Seems fair.
